### PR TITLE
Milestone: Friendship v2

### PR DESCRIPTION
**Pull request by KumarAmitt**
Major implementation in this Pull Request:-
-- Implement mutual friendships
-- Display the list of mutual friends between the current user and his friend

**Implement all feasible changes requested by previous TSEs**

-- Any feedback or suggestions to improve this project is highly appreciated.

### CODE REVIEW

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

### Hello @KumarAmitt and @keneogu, Great job! 👏  Both of you have done an awesome job so far 👌. 
* Excellent use of shoulda-matchers and capybara in your specs 👏 
* Great use of helper methods to strip logic from your views

There are still some changes that are necessary for this milestone to be approved.

- [ ]  Kindly remove the comments in your `user` model, since it’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
See this [post](https://stackoverflow.com/questions/13130859/inline-comments-in-ruby/13130900#:~:text=No%2C%20Ruby%20does%20not%20have,comment%20out%20the%20one%20row), about why comments are discouraged.

- [ ] Please do not disable rubocop, try to refactor your code to align with Ruby standards instead of disabling rubocop.

- [ ] Your `#confirm_friend` method inside the User model looks good, however it can be improved, since it will not be involving any need to use the `find` keyword which adds to the complexity of the method.
```ruby
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```

- [ ] Thanks to the above method, we can find user friends only by user_id in friendships table
```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```
With this, you will no longer need the ruby `#friends` method.

- [ ] User `#pending_friends` can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```
With this, you will no longer need the ruby `#pending_friends` method.

- [ ] User `#friend_requests` can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```

- [ ] In order to get all posts written by user on their friends, students can use simple method in User model (in order to NOT do it with Enumerables). I know this part works well in your app, but following MVC pattern we try as much as possible to keep all business logic in models and let controller just do the work of connecting the models and views. 
```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends.to_a << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```
With this method you will simply have
```ruby
  def timeline_posts
    @timeline_posts ||= current_user.friends_and_own_posts.ordered_by_most_recent.includes(:user)
  end
```

- [ ] There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it.  
See affected files below:
> `layouts/application.html.erb`
> `users/show.html.erb`

**The Resources below may come in handy**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [Rails View Helpers Best Practices](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4)
( [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright)

- [ ] Your ReadMe file still carries the app template description. "This repo includes initial code for social media app with basic styling. Its purpose is to be a starting point for Microverse students." I am sure you will agree with me, this repo no longer carries initial code, you have done a lot. Do well to update it to reflect what the app is all about. Possibly a screenshot too, to give it that professional look. Don't forget to add Authors too and other TBA except the Live Demo

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or reply to this thread, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:full_moon:
**Hi team!
Great job so far. Thank you for improving the readme as highlighted by the last reviewer:clap::clap:. However, we still need to make a few changes to get this project approved:muscle:.**

**Mandatory requirements**

- [ ] Kindly revisit the changes requested by the last reviewer on both friendship and user model. Please implement all the changes. 

- [ ] There's still logic in application.html.erb in view. As already highlighted by the last reviewer. There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it. Kindly move the logic to a helper.

Make the above-required changes and when you are ready, request another review.
Kindly drop your questions :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy coding:blush:
Eric Enaburekhan

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @keneogu and @KumarAmitt 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

- Please work on first TSE suggested changes
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by KumarAmitt** [comment]
Hi @umairarshadbutt 
Thanks for your valuable efforts in reviewing this project.
I would like to request you to kindly elaborate in detail on the changes you want us to make in this project.

**Comment by umairarshadbutt** [comment]
Hi @KumarAmitt
Following functionality should work in browser
- Request for Friendship
- Accept/Reject
- See the post

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED 🔴 ⚠️** 

## Hey @keneogu & @KumarAmitt, 👋🏽 
 **Thank you for the good job you got going on. The app runs just fine and meets some of the requirements.**

## REQUIRED CHANGES

I'll explain to you the benefits of using SQL queries instead of ruby methods.

- [ ] when friendship is confirmed, an additional row with reversed user-friend pair should be created. The point of adding two rows per friendship is to avoid having to construct the list of friends with a double query as you do in the `friend` and `confirm_friend` methods in the user model. You need to also have another row for the pending friendships.  You can do something like this.
```
has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships


# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend

```
- Remove all the methods except `friends_and_own_posts` in the user model that are taken care of by the respective SQL queries created.

- [x] There is some logic in the views folder (application.html.rb).  Remove the logic from the view files and transfer to te helpers method. View files are only meant to render pages to users and not perform any logic.

**Kindly make all the requested changes and submit another CRR. 👍🏽** 

## Cheers!! 🍹 & Happy Coding.

# Reach me on slack for a chitchat 🆘  **Roy Mukuye**

**Review by oloomoses — APPROVED** [review]
# Congratulations, Project Approved. :muscle: :tada: :clap: 
**Great job working on the suggested changes from the previous review.
You have passed all the requirements for this milestone :muscle: 
Feel free to merge and close this pull request.**

**I wish you the best in your next project and see you at the top :rocket:** 
#### Happy Coding
_Slack: Oloo Moses_

**Comment by oloomoses** [comment]
# This project has already been approved but the status on the dashboard still reads changes required. If you happen to review it kindly approve it on the dashboard to enable the team to submit the completion form.

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Amit Kumar & Kene Oguagbaka** 
Amazing job with your first submission for this project :muscle:  :muscle:
It's almost perfect :clap: :clap: :clap:  
Just one last detail to improve before you can go ahead:

- [ ] In your tests, use only one "expect" for each "scenario".
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by lekegitrepo — APPROVED** [review]
## Status: Approved :heavy_check_mark:
### Hello Team,
#### This project has been approved by @oloomoses. I guess there is confusion here. However, I'm going to approve this project. This project is approved :white_check_mark:

#### _Reviewed by Temitayo Adeleke_

**Pull request merged**
